apiVersion: v1
kind: Service
metadata:
  name: nest-ip # Service의 이름
  labels:
    app: nest-ip
spec:
  type: NodePort
  ports:
    - port: 80 # Service의 Port
      targetPort: 3000 # Pod의 Port
      protocol: TCP
      name: http
  selector:
    app: nest-ip # Pod의 Label과 일치해야 함
    serviceName: nest-ip # Service의 이름
  externalTrafficPolicy: Cluster # 클러스터에 있는 모든 Pod에 Routing하도록 설정
  sessionAffinity: None # 세션을 유지하지 않도록 설정
